server:
  port: 8082

logging:
  config: classpath:logback.xml

# xxl-job executor 配置
xxl:
  job:
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin
    accessToken: default_token
    executor:
      appName: kwseeker-executor
      address:
      ip:
      port: 10000
      logPath: /home/lee/mywork/java/xxl-job-analysis/log/jobHandler
      logRetentionDays: 30